### ISSUE TITLE
Indentify nginx reporting server version

### ISSUE THREAD

**Issue by pete-rai** [bit-broker/charts#12]
During the Cisco pentration a nginx server was identified which was returning a verbose server version. Which nginx server is this? It is with ORY? This issue is to first find this server and then silence is verbose output.

**Comment by jadiaconu** [comment]
After investigation, it seems the / mapping goes to bbk-apps namespace to the bbk-apps-bbk-demo-app-demo service. This service has a nginx inside and will throw 404 to anything except /. It seems a miss-configuration, it should accept it and show a not found on the UI.
