### ISSUE TITLE
JWTs mapped to ENV vars

### ISSUE THREAD

**Issue by pete-rai** [bit-broker/charts#14]
During the pen test an issues was identified:

> During testing, Synopsys observed several JWTs mapped directly as environment variables into pods operating in the cluster. This results in these affected JWTs potentially being obtained by malicious actors who are able to read environment variables, as well as accidental key leakage through logging systems, debugging tools, et 

This issue is for us to confirm that this was within the demo projects only. This is not really an issue for the demo instances, so we can accept it there. If it is also elsewhere, then please raise specific issue for those instances.

**Comment by jgwalker** [comment]
Can confirm this is for the examples only (connectors and example apps).
Specifically: 
* Sample connectors have a contributor token passed in via env var AUTHORIZE_KEY; this is subsequently used in contribution API calls (header 'x-bbk-auth-token')
* Both example apps have a token (jwt), policy name & description passed in for each of the same four sample policies. These are exposed directly in the UI of the explorer app, so there is no requirement for them to be secret per-se.

No JWTs for contributors or user access are handled as env vars in the BBK core services.

**Comment by pete-rai** [comment]
Closed as per James' comments
